with mbr_auto_renewal as (
SELECT
AR.CLUB_CODE,
AR.MEMBER_NUM,
AR.BILL_PLAN_C_OLD,
AR.BILL_PLAN_X_OLD,
AR.BILL_PLAN_C_NEW,
AR.BILL_PLAN_X_NEW,
AR.RPT_TXN_T AS TRANSACTION_TIME,
AR.PAYMENT_T AS PAYMENT_TIME,
AR.TRANSACTION_TYPE,
AR.CLUB_JOIN_YEAR,
cast(CASE WHEN AR.EMPLOYEE_ID = 0 AND AR.AUTH_EMPLOYEE_ID = 999999 THEN 9999
                       WHEN AR.EMPLOYEE_ID = 0 AND AR.AUTH_EMPLOYEE_ID > 0 AND AR.AUTH_EMPLOYEE_ID <> 999999  THEN AR.AUTH_EMPLOYEE_ID
                                                      ELSE AR.EMPLOYEE_ID
           END AS int) AS EMPLOYEE_ID,
cast(CASE WHEN AR.EMPLOYEE_ID = 0 AND AR.AUTH_EMPLOYEE_ID = 999999 THEN 36 ELSE AR.BRANCH_NUMBER END AS int) AS BRANCH_NUMBER,
cast(CASE WHEN AR.EMPLOYEE_ID = 0 AND AR.AUTH_EMPLOYEE_ID = 999999 THEN '36' ELSE AR.EMPLOYEE_SECTION END AS varchar)  AS EMPLOYEE_SECTION,
AR.MEMBERSHIP_EFF_DATE,
AR.ROLE_CODE,
AR.CUSTOMER_ID,
AR.AUTH_DATE as AUTH_DATE,
AR.AUTH_SOURCE,
AR.AUTH_EMPLOYEE_ID,
AR.REGION_NUMBER,
(CASE WHEN AR.AUTH_SOURCE = 'GF' THEN 'T'
             WHEN AR.AUTH_DATE IS NOT NULL AND date_diff('day', cast(AR.TRANSACTION_TIME as date),AR.AUTH_DATE) < 31 THEN 'T'
             WHEN AR.AUTH_DATE IS NOT NULL AND date_diff('day', cast(AR.TRANSACTION_TIME as date),AR.AUTH_DATE) > 30 THEN 'N'
             ELSE 'F'
END) AS AUTH_FLAG,          
(CASE WHEN AR.AUTH_SOURCE = 'GF' THEN 'T'
            WHEN AR.AUTH_DATE IS NOT NULL AND date_diff('day', cast(AR.TRANSACTION_TIME as date),AR.AUTH_DATE) < 61 THEN 'T'
            ELSE 'F'
END) AS AUTH_SIXTY_FLAG,                      
(CASE WHEN AR.TRANSACTION_TYPE = 'NEW' THEN 'T' ELSE 'F' END) AS NEW_MBR_FLAG,   
(CASE WHEN TRIM(AR.TRANSACTION_TYPE) = 'NEW' AND  TRIM(AR.BILL_PLAN_C_NEW) IN ('AC', 'AH','MP')  THEN 0   
            WHEN TRIM(AR.TRANSACTION_TYPE) <> 'NEW' AND  TRIM(AR.BILL_PLAN_C_NEW) IN ('AC', 'AH') AND date_diff('day', AR.MEMBERSHIP_EFF_DATE, cast(AR.TRANSACTION_TIME as date) ) <= 0 THEN 0
            WHEN TRIM(AR.TRANSACTION_TYPE) <> 'NEW' AND  TRIM(AR.BILL_PLAN_C_NEW) IN ('AC', 'AH') AND date_diff('day', AR.MEMBERSHIP_EFF_DATE, cast(AR.TRANSACTION_TIME as date) ) > 0 AND cast(AR.TRANSACTION_TIME AS DATE) <= date_add('month',12,AR.MEMBERSHIP_EFF_DATE) THEN 1
            WHEN TRIM(AR.TRANSACTION_TYPE) <> 'NEW' AND  TRIM(AR.BILL_PLAN_C_NEW) IN ('AC', 'AH') AND date_diff('day', AR.MEMBERSHIP_EFF_DATE, cast(AR.TRANSACTION_TIME as date) ) > 0 AND cast(AR.TRANSACTION_TIME AS DATE) > date_add('month',12,AR.MEMBERSHIP_EFF_DATE) AND cast(AR.TRANSACTION_TIME AS DATE) <= date_add('month',24,AR.MEMBERSHIP_EFF_DATE) THEN 2
            WHEN TRIM(AR.TRANSACTION_TYPE) <> 'NEW' AND  TRIM(AR.BILL_PLAN_C_NEW) IN ('AC', 'AH') AND date_diff('day', AR.MEMBERSHIP_EFF_DATE, cast(AR.TRANSACTION_TIME as date) ) > 0 AND cast(AR.TRANSACTION_TIME AS DATE) > date_add('month',24,AR.MEMBERSHIP_EFF_DATE) THEN 3
            ELSE NULL          
END) AS TENURE_N,
ar.member_name,
ar.member_tel_no,
(CASE WHEN AR.EMPLOYEE_ID IN (9999,999999,888888,490989)  THEN 'T'
                       WHEN AR.EMPLOYEE_ID = 0 AND AR.AUTH_EMPLOYEE_ID IN (9999,999999,888888,490989)  THEN 'T'
                       ELSE 'F'
END)  AS INTERNET_FLAG,  
AR.EXTRACT_T,
(CASE WHEN AR.AUTH_DATE IS NULL THEN NULL
            WHEN AR.AUTH_DATE > cast(AR.PAYMENT_T AS DATE) THEN AR.AUTH_DATE
                                           WHEN AR.AUTH_DATE < cast(AR.PAYMENT_T AS DATE) THEN cast(AR.PAYMENT_T AS DATE)
                                           ELSE AR.AUTH_DATE END) AS REPORTING_DATE
FROM member_services_mart.membership_auto_renewal AR)